services:
  db:
    image: postgres:16
    container_name: timetracker_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: timetracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
